using System.Text.Json;
using KernelOS.Core.Filesystem;
namespace KernelOS.Infrastructure;
public sealed class LocalFilesystemCapability(IFilesystemRootResolver roots) : IFilesystemCapability
{
 public Task<FilesystemOperationResult> ExecuteAsync(string operation,IReadOnlyDictionary<string,JsonElement> arguments,CancellationToken cancellationToken=default){if(cancellationToken.IsCancellationRequested)return Task.FromResult(new FilesystemOperationResult(false,"cancelled"));if(!arguments.TryGetValue("path",out var value)||value.ValueKind!=JsonValueKind.String||string.IsNullOrWhiteSpace(value.GetString()))return Task.FromResult(new FilesystemOperationResult(false,"invalid_arguments"));if(!roots.TryResolvePath(value.GetString()!,out var path))return Task.FromResult(new FilesystemOperationResult(false,"unauthorized"));try{return Task.FromResult(operation switch {"exists"=>new FilesystemOperationResult(true,null,new{exists=File.Exists(path)||Directory.Exists(path)}),"resolve"=>new FilesystemOperationResult(true,null,new{path}),"metadata"=>Metadata(path),"search" or "list"=>List(path,arguments),_=>new FilesystemOperationResult(false,"invalid_operation")});}catch(UnauthorizedAccessException){return Task.FromResult(new FilesystemOperationResult(false,"unauthorized"));}catch(DirectoryNotFoundException){return Task.FromResult(new FilesystemOperationResult(false,"not_found"));}catch(PathTooLongException){return Task.FromResult(new FilesystemOperationResult(false,"invalid_arguments"));}catch(ArgumentException){return Task.FromResult(new FilesystemOperationResult(false,"invalid_arguments"));}catch(IOException){return Task.FromResult(new FilesystemOperationResult(false,"io_error"));}}
 private static FilesystemOperationResult Metadata(string path){if(File.Exists(path)){var x=new FileInfo(path);return new(true,null,new FilesystemMetadata(x.Name,x.FullName,x.Length,x.CreationTimeUtc,x.LastWriteTimeUtc,x.Extension,"file"));}if(Directory.Exists(path)){var x=new DirectoryInfo(path);return new(true,null,new FilesystemMetadata(x.Name,x.FullName,0,x.CreationTimeUtc,x.LastWriteTimeUtc,"","directory"));}return new(false,"not_found");}
 private static FilesystemOperationResult List(string path,IReadOnlyDictionary<string,JsonElement> a){if(!Directory.Exists(path))return new(false,"not_found");var p=a.TryGetValue("pattern",out var q)&&q.ValueKind==JsonValueKind.String?q.GetString()??"*":"*";var r=a.TryGetValue("recursive",out var z)&&z.ValueKind==JsonValueKind.True;var max=a.TryGetValue("maxResults",out var n)&&n.TryGetInt32(out var m)?Math.Clamp(m,1,1000):100;var e=Directory.EnumerateFileSystemEntries(path,p,r?SearchOption.AllDirectories:SearchOption.TopDirectoryOnly).OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).Take(max).Select(x=>new FilesystemEntry(Path.GetFileName(x),x,Directory.Exists(x)?"directory":"file",File.Exists(x)?new FileInfo(x).Length:0,File.GetLastWriteTimeUtc(x))).ToArray();return new(true,null,new FilesystemSearchResult(e));}
}
