using System.Text.Json;
using KernelOS.Core;
using KernelOS.Core.Execution;
using KernelOS.Core.Planning;
using KernelOS.Infrastructure;
using KernelOS.Infrastructure.Execution;
using KernelOS.Tools;
using Microsoft.Extensions.Options;

namespace KernelOS.Tests;

public sealed class ExecutionPolicyTests
{
    [Fact] public void PolicyAllowsKnownReadOnlyTool() => Assert.Equal(ExecutionPolicyDecisionType.Allow, Policy().Evaluate(Request(new(true, false, false, ExecutionRiskLevel.Low))).Type);
    [Fact] public void PolicyRequiresConfirmationForSideEffects() { var decision = Policy().Evaluate(Request(new(false, true, false, ExecutionRiskLevel.High))); Assert.Equal(ExecutionPolicyDecisionType.RequireConfirmation, decision.Type); Assert.Equal(ExecutionPolicyReason.SideEffectRequiresConfirmation, decision.Reason); }
    [Fact] public void PolicyDeniesExplicitlyDeniedTool() => Assert.Equal(ExecutionPolicyDecisionType.Deny, Policy().Evaluate(Request(new(false, true, true, ExecutionRiskLevel.Critical))).Type);
    [Fact] public void PolicyFailsClosedForUnknownTool() => Assert.Equal(ExecutionPolicyDecisionType.RequireConfirmation, Policy().Evaluate(Request(null)).Type);
    [Fact] public void PolicyFailsClosedForInsufficientMetadata() { var decision = Policy().Evaluate(Request(new(false, false, false, ExecutionRiskLevel.Medium))); Assert.Equal(ExecutionPolicyDecisionType.RequireConfirmation, decision.Type); Assert.Equal(ExecutionPolicyReason.UnknownToolRequiresConfirmation, decision.Reason); }
    [Fact] public void PolicyRejectsInvalidRequest() => Assert.Equal(ExecutionPolicyReason.InvalidRequest, Policy().Evaluate(new(Guid.Empty, Guid.Empty, "", null)).Reason);

    [Fact] public async Task ApprovalIsScopedAndOneShot() { var store = Store(); var task = CreateTask("write"); var approval = await store.CreateAsync(Guid.NewGuid(), task.Id, ExecutionTaskFingerprint.Create(task)); Assert.False(await store.TryConsumeAsync(approval.Id, Guid.NewGuid(), task.Id, approval.TaskFingerprint)); Assert.True(await store.TryConsumeAsync(approval.Id, approval.PlanId, task.Id, approval.TaskFingerprint)); Assert.False(await store.TryConsumeAsync(approval.Id, approval.PlanId, task.Id, approval.TaskFingerprint)); }
    [Fact] public async Task ApprovalExpiresAtItsExactExpiryBoundary() { var clock = new TestTimeProvider(); var store = Store(clock, 1); var task = CreateTask("write"); var approval = await store.CreateAsync(Guid.NewGuid(), task.Id, ExecutionTaskFingerprint.Create(task)); clock.Advance(TimeSpan.FromMinutes(1)); Assert.False(await store.TryConsumeAsync(approval.Id, approval.PlanId, task.Id, approval.TaskFingerprint)); }
    [Fact] public async Task ApprovalCannotBeConsumedTwiceConcurrently() { var store = Store(); var task = CreateTask("write"); var approval = await store.CreateAsync(Guid.NewGuid(), task.Id, ExecutionTaskFingerprint.Create(task)); var results = await System.Threading.Tasks.Task.WhenAll(Enumerable.Range(0, 64).Select(_ => store.TryConsumeAsync(approval.Id, approval.PlanId, task.Id, approval.TaskFingerprint))); Assert.Equal(1, results.Count(result => result)); }
    [Fact] public void FingerprintIsDeterministicAndProtectsArguments() { var first = CreateTask("write", new Dictionary<string, JsonElement> { ["b"] = JsonSerializer.SerializeToElement(new { nested = new { b = 2, a = 1 } }), ["a"] = JsonSerializer.SerializeToElement(1) }); var reordered = CreateTask("write", new Dictionary<string, JsonElement> { ["a"] = JsonSerializer.SerializeToElement(1), ["b"] = JsonSerializer.SerializeToElement(new { nested = new { a = 1, b = 2 } }) }); var changed = first with { Arguments = new Dictionary<string, JsonElement> { ["a"] = JsonSerializer.SerializeToElement(3) } }; using var arrayDocument = JsonDocument.Parse("[1,2]"); var changedArray = first with { Arguments = new Dictionary<string, JsonElement> { ["items"] = arrayDocument.RootElement.Clone() } }; Assert.Equal(ExecutionTaskFingerprint.Create(first), ExecutionTaskFingerprint.Create(reordered)); Assert.NotEqual(ExecutionTaskFingerprint.Create(first), ExecutionTaskFingerprint.Create(changed)); Assert.NotEqual(ExecutionTaskFingerprint.Create(first), ExecutionTaskFingerprint.Create(first with { ToolName = "other" })); Assert.NotEqual(ExecutionTaskFingerprint.Create(first), ExecutionTaskFingerprint.Create(changedArray)); }

    [Fact] public async Task GateRequiresApprovalForSideEffectAndAllowsValidScopedApproval() { var planId = Guid.NewGuid(); var task = CreateTask("write"); var store = Store(); var gate = Gate(store, "write", new(false, true, false, ExecutionRiskLevel.High)); Assert.Equal(ExecutionGateStatus.RequiresConfirmation, (await gate.EvaluateAsync(planId, task, null)).Status); var approval = await store.CreateAsync(planId, task.Id, ExecutionTaskFingerprint.Create(task)); Assert.Equal(ExecutionGateStatus.Authorized, (await gate.EvaluateAsync(planId, task, approval.Id)).Status); }
    [Fact] public async Task GateDoesNotLetApprovalBypassDeny() { var planId = Guid.NewGuid(); var task = CreateTask("blocked"); var store = Store(); var approval = await store.CreateAsync(planId, task.Id, ExecutionTaskFingerprint.Create(task)); Assert.Equal(ExecutionGateStatus.Denied, (await Gate(store, "blocked", new(false, true, true, ExecutionRiskLevel.Critical)).EvaluateAsync(planId, task, approval.Id)).Status); }
    [Fact] public async Task GateDoesNotLetApprovalTrustUnknownTool() { var planId = Guid.NewGuid(); var task = CreateTask("unknown"); var store = Store(); var approval = await store.CreateAsync(planId, task.Id, ExecutionTaskFingerprint.Create(task)); var gate = new ExecutionGate(Policy(), store, new TestRegistry()); Assert.Equal(ExecutionGateStatus.RequiresConfirmation, (await gate.EvaluateAsync(planId, task, approval.Id)).Status); Assert.True(await store.TryConsumeAsync(approval.Id, planId, task.Id, approval.TaskFingerprint)); }

    [Fact] public async Task DirectGatewayDoesNotExecuteSideEffects() { var router = new FakeRouter(ToolExecutionResult.Success("ok")); var gateway = new ReadOnlyToolExecutionGateway(Policy(), new TestRegistry(new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))), router); var result = await gateway.ExecuteAsync(new ToolExecutionRequest("write", new Dictionary<string, JsonElement>())); Assert.Equal(ToolExecutionStatus.Unauthorized, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task DirectGatewayExecutesKnownReadOnlyTools() { var router = new FakeRouter(ToolExecutionResult.Success("ok")); var gateway = new ReadOnlyToolExecutionGateway(Policy(), new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low))), router); var result = await gateway.ExecuteAsync(new ToolExecutionRequest("read", new Dictionary<string, JsonElement>())); Assert.Equal(ToolExecutionStatus.Success, result.Status); Assert.Equal(1, router.Calls); }
    [Fact] public async Task ExecutorBlocksSideEffectWithoutApproval() { var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await Executor(Store(), "write", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(Plan(CreateTask("write"))); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ExecutorExecutesApprovedSideEffectAndRejectsChangedTask() { var task = CreateTask("write"); var plan = Plan(task); var store = Store(); var approval = await store.CreateAsync(plan.Id, task.Id, ExecutionTaskFingerprint.Create(task)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var executor = Executor(store, "write", new(false, true, false, ExecutionRiskLevel.High), router); Assert.Equal(PlannerStatus.Completed, (await executor.ExecuteAsync(plan, new Dictionary<Guid, Guid> { [task.Id] = approval.Id })).Status); var changed = task with { ToolName = "other" }; var secondPlan = Plan(changed); var approval2 = await store.CreateAsync(secondPlan.Id, changed.Id, ExecutionTaskFingerprint.Create(task)); Assert.Equal(PlannerStatus.RequiresConfirmation, (await Executor(store, "other", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(secondPlan, new Dictionary<Guid, Guid> { [changed.Id] = approval2.Id })).Status); Assert.Equal(1, router.Calls); }
    [Fact] public async Task ExecutorPreflightsMultiTaskConfirmationWithoutExecutingAnyTask() { var first = CreateTask("read"); var second = CreateTask("write"); var third = CreateTask("read"); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var tools = new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))); var store = Store(); var executor = new PlanExecutor(new ExecutionGate(Policy(), store, tools), router); var result = await executor.ExecuteAsync(Plan(first, second, third)); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); Assert.All(result.Plan!.Tasks, task => Assert.Equal(PlannerStatus.Planned, task.Status)); }
    [Fact] public async Task ExecutorRejectsPreflightPlanInsteadOfExecutingAnyTask() { var first = CreateTask("read"); var second = CreateTask("write"); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var tools = new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))); var executor = new PlanExecutor(new ExecutionGate(Policy(), Store(), tools), router); var partial = await executor.ExecuteAsync(Plan(first, second)); var retry = await executor.ExecuteAsync(partial.Plan!); Assert.Equal(PlannerStatus.RequiresConfirmation, partial.Status); Assert.Equal(PlannerStatus.Failed, retry.Status); Assert.Equal("invalid_plan", retry.Error!.Code); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ExecutorPreflightDenyTakesPrecedenceOverConfirmationWithoutExecutingTools() { var read = CreateTask("read"); var confirm = CreateTask("write"); var denied = CreateTask("blocked"); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var tools = new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("write", new(false, true, false, ExecutionRiskLevel.High)), new TestTool("blocked", new(false, true, true, ExecutionRiskLevel.Critical))); var result = await new PlanExecutor(new ExecutionGate(Policy(), Store(), tools), router).ExecuteAsync(Plan(read, confirm, denied)); Assert.Equal(PlannerStatus.Denied, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ExecutorPreflightUnknownLaterTaskDoesNotExecuteEarlierAllowedTask() { var read = CreateTask("read"); var unknown = CreateTask("missing"); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var gate = new ExecutionGate(Policy(), Store(), new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low)))); var executor = new PlanExecutor(gate, router); var result = await executor.ExecuteAsync(Plan(read, unknown)); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task MultiTaskPendingApprovalExecutesSnapshotInOrderOnce() { var first = CreateTask("read"); var second = CreateTask("write"); var third = CreateTask("read"); var plan = Plan(first, second, third); var clock = new TestTimeProvider(); var approvals = Store(clock); var pendingStore = new InMemoryExecutionPendingStore(Options.Create(new ExecutionPolicyOptions { ApprovalTtlMinutes = 5 }), clock); var tools = new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))); var confirmations = new ExecutionConfirmationService(Policy(), approvals, pendingStore, tools, clock, Options.Create(new ExecutionPolicyOptions { ApprovalTtlMinutes = 5 })); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var executor = new PlanExecutor(new ExecutionGate(Policy(), approvals, tools), router); Assert.Equal(PlannerStatus.RequiresConfirmation, (await executor.ExecuteAsync(plan)).Status); var pending = await confirmations.CreatePendingAsync(plan, second.Id); Assert.Equal(3, pending.Confirmation!.TaskCount); Assert.Equal(PendingExecutionStatus.Approved, (await confirmations.DecideAsync(pending.Confirmation.PendingExecutionId, ExecutionConfirmationDecision.Approve))!.Status); Assert.Equal(0, router.Calls); var stored = await confirmations.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId); Assert.NotNull(stored); Assert.Equal(PlannerStatus.Completed, (await executor.ExecuteAsync(stored!.Plan, stored.ApprovalIds)).Status); Assert.Equal(["read", "write", "read"], router.Requests.Select(x => x.ToolName)); Assert.Null(await confirmations.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId)); }
    [Fact] public async Task MultiTaskConfirmationCreatesScopedApprovalsForEachTask() { var first = CreateTask("write"); var second = CreateTask("write"); var plan = Plan(first, second); var clock = new TestTimeProvider(); var approvals = Store(clock); var store = new InMemoryExecutionPendingStore(Options.Create(new ExecutionPolicyOptions { ApprovalTtlMinutes = 5 }), clock); var tools = new TestRegistry(new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))); var service = new ExecutionConfirmationService(Policy(), approvals, store, tools, clock, Options.Create(new ExecutionPolicyOptions { ApprovalTtlMinutes = 5 })); var pending = await service.CreatePendingAsync(plan, first.Id); Assert.Equal(2, pending.Confirmation!.TaskCount); var approved = await service.DecideAsync(pending.Confirmation.PendingExecutionId, ExecutionConfirmationDecision.Approve); Assert.Equal(PendingExecutionStatus.Approved, approved!.Status); var snapshot = await service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId); Assert.Equal(2, snapshot!.ApprovalIds!.Count); Assert.NotEqual(snapshot.ApprovalIds[first.Id], snapshot.ApprovalIds[second.Id]); }
    [Fact] public async Task ExecutorFailsFastAfterAuthorizedMultiTaskPreflight() { var first = CreateTask("first"); var second = CreateTask("second"); var third = CreateTask("third"); var router = new FakeRouter(request => request.ToolName == "second" ? ToolExecutionResult.Failure() : ToolExecutionResult.Success("ok")); var tools = new TestRegistry(new TestTool("first", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("second", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("third", new(true, false, false, ExecutionRiskLevel.Low))); var result = await new PlanExecutor(new ExecutionGate(Policy(), Store(), tools), router).ExecuteAsync(Plan(first, second, third)); Assert.Equal(PlannerStatus.Failed, result.Status); Assert.Equal(["first", "second"], router.Requests.Select(request => request.ToolName)); Assert.Equal([PlannerStatus.Completed, PlannerStatus.Failed, PlannerStatus.Planned], result.Plan!.Tasks.Select(task => task.Status)); }
    [Fact] public async Task MultiTaskPendingExecutesOriginalSnapshotAfterOriginalArgumentsAreMutated() { var originalItems = new List<string> { "original", "values" }; var originalArguments = new Dictionary<string, JsonElement> { ["payload"] = JsonSerializer.SerializeToElement(new { items = originalItems, nested = new { value = "original" } }) }; var first = CreateTask("write", originalArguments); var second = CreateTask("write", new Dictionary<string, JsonElement> { ["payload"] = JsonSerializer.SerializeToElement(new { items = new List<string> { "second" } }) }); var originalTasks = new List<PlanTask> { first, second }; var plan = new Plan(Guid.NewGuid(), Guid.NewGuid(), originalTasks, PlannerStatus.Planned, null, null); var (service, approvals, tools) = ConfirmationFixture(); var pending = await service.CreatePendingAsync(plan, first.Id); originalItems[0] = "mutated-list"; originalArguments["payload"] = JsonSerializer.SerializeToElement(new { items = new List<string> { "mutated" }, nested = new { value = "mutated" } }); originalTasks[1] = second with { Arguments = new Dictionary<string, JsonElement> { ["payload"] = JsonSerializer.SerializeToElement(new { items = new List<string> { "mutated-second" } }) } }; await service.DecideAsync(pending.Confirmation!.PendingExecutionId, ExecutionConfirmationDecision.Approve); var stored = Assert.IsType<PendingExecution>(await service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await new PlanExecutor(new ExecutionGate(Policy(), approvals, tools), router).ExecuteAsync(stored.Plan, stored.ApprovalIds); Assert.Equal(PlannerStatus.Completed, result.Status); Assert.Equal("{\"items\":[\"original\",\"values\"],\"nested\":{\"value\":\"original\"}}", router.Requests[0].Arguments["payload"].GetRawText()); Assert.Equal("{\"items\":[\"second\"]}", router.Requests[1].Arguments["payload"].GetRawText()); }
    [Fact] public async Task ApprovalForOneTaskDoesNotAuthorizeAnotherTask() { var first = CreateTask("write"); var second = CreateTask("write"); var plan = Plan(first, second); var approvals = Store(); var approval = await approvals.CreateAsync(plan.Id, first.Id, ExecutionTaskFingerprint.Create(first)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await Executor(approvals, "write", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(plan, new Dictionary<Guid, Guid> { [second.Id] = approval.Id }); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ApprovalWithIncorrectPlanIdDoesNotAuthorizeExecution() { var task = CreateTask("write"); var plan = Plan(task); var approvals = Store(); var approval = await approvals.CreateAsync(Guid.NewGuid(), task.Id, ExecutionTaskFingerprint.Create(task)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await Executor(approvals, "write", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(plan, new Dictionary<Guid, Guid> { [task.Id] = approval.Id }); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ApprovalWithIncorrectTaskIdDoesNotAuthorizeExecution() { var task = CreateTask("write"); var plan = Plan(task); var approvals = Store(); var approval = await approvals.CreateAsync(plan.Id, Guid.NewGuid(), ExecutionTaskFingerprint.Create(task)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await Executor(approvals, "write", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(plan, new Dictionary<Guid, Guid> { [task.Id] = approval.Id }); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ApprovalWithIncorrectFingerprintDoesNotAuthorizeExecution() { var task = CreateTask("write"); var plan = Plan(task); var approvals = Store(); var approval = await approvals.CreateAsync(plan.Id, task.Id, "incorrect-fingerprint"); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await Executor(approvals, "write", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(plan, new Dictionary<Guid, Guid> { [task.Id] = approval.Id }); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ConcurrentApprovesPerformOneTransitionAndCreateOneApprovalSet() { var first = CreateTask("write"); var second = CreateTask("write"); var plan = Plan(first, second); var (service, _, _) = ConfirmationFixture(); var pending = await service.CreatePendingAsync(plan, first.Id); var id = Assert.IsType<ExecutionConfirmationRequest>(pending.Confirmation).PendingExecutionId; var results = await Task.WhenAll(Enumerable.Range(0, 2).Select(_ => Task.Run(() => service.DecideAsync(id, ExecutionConfirmationDecision.Approve)))); Assert.Equal(1, results.Count(result => result!.Transitioned)); var approved = Assert.IsType<PendingExecution>(await service.TryTakeApprovedExecutionAsync(id)); Assert.Equal(PendingExecutionStatus.Approved, approved.Status); Assert.Equal(2, approved.ApprovalIds!.Count); }
    [Fact] public async Task ConcurrentApproveAndRejectLeaveOneTerminalState() { var task = CreateTask("write"); var plan = Plan(task); var (service, approvals, tools) = ConfirmationFixture(); var pending = await service.CreatePendingAsync(plan, task.Id); var id = Assert.IsType<ExecutionConfirmationRequest>(pending.Confirmation).PendingExecutionId; var results = await Task.WhenAll(Task.Run(() => service.DecideAsync(id, ExecutionConfirmationDecision.Approve)), Task.Run(() => service.DecideAsync(id, ExecutionConfirmationDecision.Reject))); Assert.Equal(1, results.Count(result => result!.Transitioned)); var current = Assert.IsType<ExecutionConfirmationResult>(await service.GetAsync(id)); Assert.Contains(current.Status, new[] { PendingExecutionStatus.Approved, PendingExecutionStatus.Rejected }); var stored = await service.TryTakeApprovedExecutionAsync(id); if (current.Status == PendingExecutionStatus.Rejected) Assert.Null(stored); else { var approved = Assert.IsType<PendingExecution>(stored); var router = new FakeRouter(ToolExecutionResult.Success("ok")); Assert.Equal(PlannerStatus.Completed, (await new PlanExecutor(new ExecutionGate(Policy(), approvals, tools), router).ExecuteAsync(approved.Plan, approved.ApprovalIds)).Status); Assert.Equal(1, router.Calls); } }
    [Fact] public async Task ConcurrentPendingExecutionsAreTakenAndExecutedAtMostOnce() { var first = CreateTask("write"); var second = CreateTask("write"); var plan = Plan(first, second); var (service, approvals, tools) = ConfirmationFixture(); var pending = await service.CreatePendingAsync(plan, first.Id); await service.DecideAsync(pending.Confirmation!.PendingExecutionId, ExecutionConfirmationDecision.Approve); var takes = await Task.WhenAll(Enumerable.Range(0, 2).Select(_ => Task.Run(() => service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId)))); Assert.Equal(1, takes.Count(item => item is not null)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var taken = Assert.Single(takes.Where(item => item is not null))!; Assert.Equal(PlannerStatus.Completed, (await new PlanExecutor(new ExecutionGate(Policy(), approvals, tools), router).ExecuteAsync(taken.Plan, taken.ApprovalIds)).Status); Assert.Equal(2, router.Calls); }
    [Fact] public async Task ExecutedPendingIsExplicitlyOneShotAndItsApprovalsCannotBeReused() { var task = CreateTask("write"); var plan = Plan(task); var (service, approvals, tools) = ConfirmationFixture(); var pending = await service.CreatePendingAsync(plan, task.Id); await service.DecideAsync(pending.Confirmation!.PendingExecutionId, ExecutionConfirmationDecision.Approve); var stored = await service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var executor = new PlanExecutor(new ExecutionGate(Policy(), approvals, tools), router); Assert.Equal(PlannerStatus.Completed, (await executor.ExecuteAsync(stored!.Plan, stored.ApprovalIds)).Status); Assert.Null(await service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId)); Assert.Equal(PlannerStatus.RequiresConfirmation, (await executor.ExecuteAsync(stored.Plan, stored.ApprovalIds)).Status); Assert.Equal(1, router.Calls); }
    [Fact] public async Task ExpiredPendingCannotBeApprovedOrExecuted() { var task = CreateTask("write"); var clock = new TestTimeProvider(); var (service, _, _) = ConfirmationFixture(clock, 1); var pending = await service.CreatePendingAsync(Plan(task), task.Id); clock.Advance(TimeSpan.FromMinutes(1)); Assert.Null(await service.DecideAsync(pending.Confirmation!.PendingExecutionId, ExecutionConfirmationDecision.Approve)); Assert.Null(await service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId)); }
    [Fact] public async Task PendingExpiringAfterApprovalCannotBeExecuted() { var task = CreateTask("write"); var clock = new TestTimeProvider(); var (service, _, _) = ConfirmationFixture(clock, 1); var pending = await service.CreatePendingAsync(Plan(task), task.Id); await service.DecideAsync(pending.Confirmation!.PendingExecutionId, ExecutionConfirmationDecision.Approve); clock.Advance(TimeSpan.FromMinutes(1)); Assert.Null(await service.TryTakeApprovedExecutionAsync(pending.Confirmation.PendingExecutionId)); }
    [Fact] public async Task ExpiredApprovalMakesMultiTaskPreflightRequireConfirmationWithoutExecution() { var task = CreateTask("write"); var plan = Plan(task); var clock = new TestTimeProvider(); var approvals = Store(clock, 1); var approval = await approvals.CreateAsync(plan.Id, task.Id, ExecutionTaskFingerprint.Create(task)); clock.Advance(TimeSpan.FromMinutes(1)); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var result = await Executor(approvals, "write", new(false, true, false, ExecutionRiskLevel.High), router).ExecuteAsync(plan, new Dictionary<Guid, Guid> { [task.Id] = approval.Id }); Assert.Equal(PlannerStatus.RequiresConfirmation, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task ReadingPendingDoesNotRenewItsExpiry() { var task = CreateTask("write"); var clock = new TestTimeProvider(); var (service, _, _) = ConfirmationFixture(clock, 1); var pending = await service.CreatePendingAsync(Plan(task), task.Id); clock.Advance(TimeSpan.FromSeconds(30)); Assert.NotNull(await service.GetAsync(pending.Confirmation!.PendingExecutionId)); clock.Advance(TimeSpan.FromSeconds(30)); Assert.Null(await service.GetAsync(pending.Confirmation.PendingExecutionId)); }
    [Fact] public async Task CancellationDuringMultiTaskPreflightDoesNotExecuteTools() { var first = CreateTask("read"); var second = CreateTask("write"); using var cancellation = new CancellationTokenSource(); cancellation.Cancel(); var router = new FakeRouter(ToolExecutionResult.Success("ok")); var tools = new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low)), new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))); var result = await new PlanExecutor(new ExecutionGate(Policy(), Store(), tools), router).ExecuteAsync(Plan(first, second), cancellationToken: cancellation.Token); Assert.Equal(PlannerStatus.Cancelled, result.Status); Assert.Equal(0, router.Calls); }
    [Fact] public async Task CancellationDuringMultiTaskExecutionStopsBeforeTheSecondTask() { var first = CreateTask("read"); var second = CreateTask("read"); using var cancellation = new CancellationTokenSource(); var router = new CancellingRouter(cancellation); var tools = new TestRegistry(new TestTool("read", new(true, false, false, ExecutionRiskLevel.Low))); var result = await new PlanExecutor(new ExecutionGate(Policy(), Store(), tools), router).ExecuteAsync(Plan(first, second), cancellationToken: cancellation.Token); Assert.Equal(PlannerStatus.Cancelled, result.Status); Assert.Equal(1, router.Calls); }

    private static DefaultExecutionPolicy Policy() => new();
    private static ExecutionPolicyRequest Request(ToolExecutionMetadata? metadata) => new(Guid.NewGuid(), Guid.NewGuid(), "tool", metadata);
    private static InMemoryExecutionApprovalStore Store(TestTimeProvider? clock = null, int ttl = 5) => new(Options.Create(new ExecutionPolicyOptions { ApprovalTtlMinutes = ttl }), clock ?? new TestTimeProvider());
    private static ExecutionGate Gate(IExecutionApprovalStore store, string name, ToolExecutionMetadata metadata) => new(Policy(), store, new TestRegistry(new TestTool(name, metadata)));
    private static PlanExecutor Executor(IExecutionApprovalStore store, string name, ToolExecutionMetadata metadata, IToolRouter router) => new(Gate(store, name, metadata), router);
    private static Plan Plan(params PlanTask[] tasks) => new(Guid.NewGuid(), Guid.NewGuid(), tasks, PlannerStatus.Planned, null, null);
    private static PlanTask CreateTask(string name, IReadOnlyDictionary<string, JsonElement>? arguments = null) => new(Guid.NewGuid(), "task", name, arguments ?? new Dictionary<string, JsonElement>(), PlannerStatus.Planned, 0);
    private static (ExecutionConfirmationService Service, InMemoryExecutionApprovalStore Approvals, TestRegistry Tools) ConfirmationFixture(TestTimeProvider? clock = null, int ttl = 5) { var selectedClock = clock ?? new TestTimeProvider(); var options = Options.Create(new ExecutionPolicyOptions { ApprovalTtlMinutes = ttl }); var approvals = new InMemoryExecutionApprovalStore(options, selectedClock); var tools = new TestRegistry(new TestTool("write", new(false, true, false, ExecutionRiskLevel.High))); return (new ExecutionConfirmationService(Policy(), approvals, new InMemoryExecutionPendingStore(options, selectedClock), tools, selectedClock, options), approvals, tools); }
}

internal sealed class TestRegistry(params IKernelTool[] tools) : IToolRegistry
{
    public IReadOnlyCollection<IKernelTool> Tools { get; } = tools;
    public IKernelTool? GetByName(string name) => Tools.SingleOrDefault(tool => string.Equals(tool.Name, name, StringComparison.OrdinalIgnoreCase));
    public bool Exists(string name) => GetByName(name) is not null;
    public IReadOnlyCollection<IKernelTool> FindByCategory(string category) => [];
    public IReadOnlyCollection<IKernelTool> FindByCapability(string capability) => [];
}

internal sealed class TestTool(string name, ToolExecutionMetadata metadata) : IKernelTool
{
    public string Name => name; public string Description => name; public string Category => "test"; public IReadOnlyCollection<ToolCapability> Capabilities => []; public IReadOnlyCollection<ToolParameter> Parameters => []; public ToolExecutionMetadata ExecutionMetadata => metadata;
    public Task<ToolExecutionResult> ExecuteAsync(ToolExecutionRequest request, CancellationToken cancellationToken = default) => Task.FromResult(ToolExecutionResult.Success("ok"));
}

internal sealed class TestTimeProvider : TimeProvider
{
    private DateTimeOffset now = new(2026, 8, 7, 0, 0, 0, TimeSpan.Zero);
    public override DateTimeOffset GetUtcNow() => now;
    public void Advance(TimeSpan duration) => now = now.Add(duration);
}
