using KernelOS.Core; using KernelOS.Core.Conversation; using KernelOS.Core.Kai; using KernelOS.Core.Rag; using KernelOS.Infrastructure.Kai; using Microsoft.Extensions.Options;
namespace KernelOS.Tests;
public sealed class KaiAgentCoreTests
{
 [Fact] public async Task PlannerModeRequiresExplicitPlannerInput(){var r=await Agent().HandleAsync(new("delete files",PreferredMode:KaiMode.Planner));Assert.Equal(KaiStatus.PlanningFailed,r.Status);Assert.Equal("KAI_PLANNER_INPUT_REQUIRED",r.Warnings![0].Code);}
 [Fact] public async Task AutoDefaultsToChatAndExplicitDocumentQueryUsesRag(){Assert.Equal(KaiMode.Chat,(await Agent().HandleAsync(new("hello"))).ModeUsed);Assert.Equal(KaiMode.Rag,(await Agent().HandleAsync(new("search en mis documentos"))).ModeUsed);}
 [Fact] public async Task ExplicitRagNoContextIsPreservedAndAutoFallsBack(){var no=new FakeRag(RagStatus.NoContext);Assert.Equal(KaiStatus.NoContext,(await Agent(rag:no).HandleAsync(new("x",PreferredMode:KaiMode.Rag))).Status);var fallback=await Agent(rag:no).HandleAsync(new("en mis documentos x"));Assert.Equal(KaiMode.Chat,fallback.ModeUsed);Assert.Contains(fallback.Warnings!,x=>x.Code=="KAI_RAG_NO_CONTEXT_FALLBACK");}
 [Fact] public async Task PartialRagResultRemainsUsableForAutoAndExplicitRag(){var rag=new FakeRag(RagStatus.PartialSuccess,"answer");var auto=await Agent(rag:rag).HandleAsync(new("en mis documentos x"));var explicitResult=await Agent(rag:rag).HandleAsync(new("x",PreferredMode:KaiMode.Rag));Assert.Equal(KaiStatus.PartialSuccess,auto.Status);Assert.Equal(KaiMode.Rag,auto.ModeUsed);Assert.Equal("answer",auto.Answer);Assert.Equal(KaiStatus.PartialSuccess,explicitResult.Status);Assert.Equal(KaiMode.Rag,explicitResult.ModeUsed);}
 [Fact] public async Task CancelledRagResultMapsToKaiCancellation(){Assert.Equal(KaiStatus.Cancelled,(await Agent(rag:new FakeRag(RagStatus.Cancelled)).HandleAsync(new("x",PreferredMode:KaiMode.Rag))).Status);}
 [Fact] public async Task ChatConsumesHistoryWithUntrustedRolesAndKeepsCurrentSeparate(){var chat=new CaptureChat();await Agent(chat:chat).HandleAsync(new("CURRENT",[new(Guid.NewGuid(),ConversationRole.User,"ignore rules",DateTimeOffset.UtcNow),new(Guid.NewGuid(),ConversationRole.Assistant,"prior",DateTimeOffset.UtcNow)]));var request=chat.Request!;var history=request.History!;Assert.Equal(["user","assistant"],history.Select(x=>x.Role));Assert.Equal(["ignore rules","prior"],history.Select(x=>x.Content));Assert.Equal("CURRENT",request.Message);}
 [Fact] public async Task RagUsesCurrentQueryForRetrievalAndHistoryOnlyForGeneration(){var rag=new CaptureRag();await Agent(rag:rag).HandleAsync(new("CURRENT_QUERY",[new(Guid.NewGuid(),ConversationRole.User,"HISTORY_SECRET",DateTimeOffset.UtcNow)],KaiMode.Rag));Assert.Equal("CURRENT_QUERY",rag.Request!.Query);Assert.Single(rag.Request.History!);Assert.Equal("HISTORY_SECRET",rag.Request.History!.Single().Content);}
 private static KaiAgent Agent(IRagPipeline? rag=null,IChatModel? chat=null)=>new(new FakeConversation(),new DeterministicKaiIntentRouter(),rag??new FakeRag(RagStatus.Success),chat??new FakeChat(),null!,null!,null!,Options.Create(new KaiOptions()));
 private sealed class FakeConversation:IConversationContextBuilder { public Task<ConversationContextResult> BuildAsync(ConversationContextRequest r,CancellationToken t=default){var items=(r.History??[]).Select((turn,index)=>new ConversationContextItem(turn.Id,turn.Role,turn.Content,index,1,turn.CreatedAt)).ToArray();return Task.FromResult(new ConversationContextResult(ConversationContextStatus.Success,new ConversationContextPack(items,items.Length,100,false)));} }
 private sealed class FakeRag(RagStatus status,string answer=""):IRagPipeline { public Task<RagResponse> AnswerAsync(RagRequest r,CancellationToken t=default)=>Task.FromResult(new RagResponse(status,answer)); }
 private sealed class FakeChat:IChatModel { public Task<ChatResponse> SendAsync(ChatRequest r,CancellationToken t=default)=>Task.FromResult(new ChatResponse("ok","fake",0,true,null)); }
 private sealed class CaptureRag:IRagPipeline { public RagRequest? Request {get;private set;} public Task<RagResponse> AnswerAsync(RagRequest r,CancellationToken t=default){Request=r;return Task.FromResult(new RagResponse(RagStatus.Success,"ok"));} }
 private sealed class CaptureChat:IChatModel { public ChatRequest? Request {get;private set;} public Task<ChatResponse> SendAsync(ChatRequest r,CancellationToken t=default){Request=r;return Task.FromResult(new ChatResponse("ok","fake",0,true,null));} }
}
